export const AD_ANGLES = [
  {
    id: 'pas',
    name: 'Problem-Agitate-Solution',
    tag: 'PAS',
    color: '#ef4444',
    brief: 'Name the pain, twist the knife, offer the only exit.',
  },
  {
    id: 'before-after',
    name: 'Before & After',
    tag: 'TRANSFORMATION',
    color: '#f97316',
    brief: 'Show where they are stuck vs. where they could be.',
  },
  {
    id: 'social-proof',
    name: 'Social Proof',
    tag: 'PROOF',
    color: '#10b981',
    brief: 'Real numbers, real people, real results. Specifics only.',
  },
  {
    id: 'fomo',
    name: 'FOMO / Urgency',
    tag: 'URGENCY',
    color: '#f43f5e',
    brief: 'Others are already winning. Time is running out.',
  },
  {
    id: 'curiosity-gap',
    name: 'Curiosity Gap',
    tag: 'CURIOSITY',
    color: '#8b5cf6',
    brief: 'Tease what they desperately need to know but do not yet.',
  },
  {
    id: 'direct-offer',
    name: 'Direct Offer',
    tag: 'OFFER',
    color: '#0ea5e9',
    brief: 'No fluff. What it is, the price, and exactly how to get it.',
  },
  {
    id: 'story',
    name: 'Personal Story',
    tag: 'STORY',
    color: '#ec4899',
    brief: 'First-person narrative that leads naturally to the product.',
  },
  {
    id: 'educational',
    name: 'How-To / Educational',
    tag: 'EDUCATION',
    color: '#06b6d4',
    brief: 'Teach something genuinely useful. Product is the next step.',
  },
  {
    id: 'dream-state',
    name: 'Dream State',
    tag: 'VISION',
    color: '#6366f1',
    brief: 'Paint the vivid life they want. Make them feel it already.',
  },
  {
    id: 'objection-crusher',
    name: 'Objection Crusher',
    tag: 'OBJECTION',
    color: '#84cc16',
    brief: 'Name and destroy the single biggest reason they have not bought.',
  },
  {
    id: 'contrarian',
    name: 'Contrarian',
    tag: 'PATTERN INTERRUPT',
    color: '#f59e0b',
    brief: 'Challenge a belief everyone holds. Force a full stop and rethink.',
  },
  {
    id: 'warning',
    name: 'Warning',
    tag: 'STOP DOING X',
    color: '#dc2626',
    brief: 'You are making an expensive mistake right now. Here is the cost.',
  },
  {
    id: 'authority',
    name: 'Authority / Proof',
    tag: 'AUTHORITY',
    color: '#1d4ed8',
    brief: 'Credentials, case studies, media mentions, and verifiable results.',
  },
  {
    id: 'testimonial',
    name: 'Testimonial-Style',
    tag: 'TESTIMONIAL',
    color: '#059669',
    brief: 'Written as a real customer describing their exact, specific result.',
  },
  {
    id: 'new-vs-old',
    name: 'New Way vs. Old Way',
    tag: 'CONTRAST',
    color: '#7c3aed',
    brief: 'Old way: slow, expensive, broken. New way: fast, simple, proven.',
  },
  {
    id: 'question',
    name: 'Question Hook',
    tag: 'QUESTION',
    color: '#be185d',
    brief: 'One question the target cannot honestly answer no to.',
  },
  {
    id: 'benefit-stack',
    name: 'Benefit Stack',
    tag: 'BENEFITS',
    color: '#0891b2',
    brief: 'Stack 5 to 7 specific benefits. Each one must land differently.',
  },
  {
    id: 'scarcity',
    name: 'Scarcity / Exclusivity',
    tag: 'EXCLUSIVE',
    color: '#9f1239',
    brief: 'Limited spots. Not for everyone. Act now or lose your place.',
  },
  {
    id: 'empathy',
    name: 'Empathy / Relatability',
    tag: 'EMPATHY',
    color: '#047857',
    brief: 'I was exactly where you are. I know what it costs you every day.',
  },
  {
    id: 'numbers',
    name: 'Specificity / Numbers-Led',
    tag: 'DATA',
    color: '#1e40af',
    brief: 'Lead with a specific number that stops the scroll cold.',
  },
]
